### ISSUE TITLE
Expired SSL certificate: regler.kodapor.com

### ISSUE THREAD

**Issue by kpalmvik** [mekwall/regler.kodapor.com#4]
The SSL certificate presented by `https://regler.kodapor.com/` is currently a [Let's Encrypt Authority X3` that expired on 17 March 2017](https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=10661519).

This prevent visitors from using the site, unless they click through security warnings in their browser.

**Comment by mekwall** [comment]
It's been fixed! For some reason the auto-renewal script wasn't working as it was supposed to :(
