### ISSUE TITLE
Lokala kodapor för mindre orter. 

### ISSUE THREAD

**Issue by tomasforsman** [mekwall/regler.kodapor.com#5]
Det är kanske inte relevant för sth, gtb och Malmö, men det vore intressant med en lokal Kodapor - Växjö, mest med syfte att bygga lokalt Community och annordna träffar. Tanken är då att I stor utsträckning undvika att köra liknande trådar som i huvud gruppen om det inte riktar sig till det mer lokala. 

Är detta något som funderat över?

**Comment by annafay** [comment]
Ber om ursäkt för ett alldeles för sent svar. Om syftet är att bjuda in till lokala träffar ser vi idag gärna att inbjudningarna sker i huvudgruppen. De kan vara intressanta även för utsocknes och i dagsläget är vi ändå inte översållade med dem ändå. Det kan dessutom vara bra för kodapor i storstäderna att se att det händer saker utanför tullarna.
